import os
from datetime import datetime
from typing import Dict


class MarkdownReporter:
    def __init__(self):
        """Initialize markdown reporter"""
        pass
    
    def generate_report(self, results: Dict, output_file: str) -> str:
        """Generate markdown report from batch processing results"""
        
        markdown = self._build_header(results)
        markdown += self._build_questions_section(results)
        markdown += self._build_metadata_section(results)
        
        # Write to file
        os.makedirs(os.path.dirname(output_file) or ".", exist_ok=True)
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(markdown)
        
        print(f"[REPORT GENERATED] {output_file}")
        return output_file
    
    def _build_header(self, results: Dict) -> str:
        """Build report header"""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        header = f"""# Journal Research Report

**Generated:** {timestamp}

---

"""
        return header
    
    def _build_questions_section(self, results: Dict) -> str:
        """Build questions and papers section"""
        section = ""
        
        for i, q_result in enumerate(results.get("questions", []), 1):
            question = q_result.get("question", "")
            status = q_result.get("status", "unknown")
            papers = q_result.get("papers", [])
            errors = q_result.get("errors", [])
            
            section += f"## Research Question {i}\n\n"
            section += f"**Question:** {question}\n\n"
            section += f"**Status:** {status}\n\n"
            
            if errors:
                section += f"**Errors:** {', '.join(errors)}\n\n"
            
            if papers:
                section += f"### Papers Found ({len(papers)})\n\n"
                for j, paper in enumerate(papers, 1):
                    section += f"#### Paper {j}: {paper.get('title', 'Untitled')}\n\n"
                    section += f"- **URL:** [{paper.get('url', 'N/A')}]({paper.get('url', '#')})\n"
                    
                    if paper.get('content'):
                        # Truncate content to first 500 chars
                        content_preview = paper['content'][:500]
                        section += f"- **Preview:** {content_preview}...\n\n"
                    else:
                        section += "- **Preview:** No content available\n\n"
            else:
                section += "### No papers found\n\n"
            
            section += "---\n\n"
        
        return section
    
    def _build_metadata_section(self, results: Dict) -> str:
        """Build metadata section"""
        total_questions = len(results.get("questions", []))
        total_papers = results.get("total_papers_found", 0)
        total_errors = results.get("total_errors", 0)
        
        metadata = f"""## Metadata

- **Total Questions:** {total_questions}
- **Total Papers Found:** {total_papers}
- **Total Errors:** {total_errors}
- **Processing Status:** {results.get('processing_status', 'unknown')}

---

*Report generated by Journal Finder Enhancement System*
"""
        
        return metadata
